### ISSUE TITLE
Use vib for container building?

### ISSUE THREAD

**Issue by tomirgang** [Elektrobit/ebcl_dev_container#18]
I started to use Vanilla OS and took a deep look at [vib](https://docs.vanillaos.org/collections/vib).
It seems like a quite cool tool for building containers, and maybe it's worth to move form the home-grown Python build tool to vib.

**Comment by tomirgang** [comment]
Hi @matthiasb85, Hi @simone-weiss,

any opinion on this?

Regards,
Thomas

**Comment by simone-weiss** [comment]
@tomirgang  As vib is rather exotic and small, no

**Comment by simone-weiss** [comment]
Decided against
